# Generated by Django 4.0.4 on 2022-04-17 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbcep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='Hotel_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dbcep.hotel_branches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_branches',
            name='user',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='Hotel_id',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='dbcep.hotel_branches'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=20, null=True)),
                ('relationship', models.CharField(max_length=100, null=True)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcep.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssn', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('Hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcep.hotel_branches')),
                ('Room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcep.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookingtype', models.IntegerField()),
                ('Hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcep.hotel_branches')),
                ('Room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbcep.rooms')),
            ],
        ),
    ]
