# Generated by Django 4.0.4 on 2022-05-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcep', '0003_remove_booking_hotel_id_booking_book_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='hotel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbcep.hotel_branches'),
            preserve_default=False,
        ),
    ]
